export { ReactComponent as DefaultImage } from "./default.svg";
export { ReactComponent as EthImage } from "./Eth.svg";
export { ReactComponent as ETHTestnetImage } from "./ETHTestnet.svg";
export { ReactComponent as PolygonImage } from "./Polygon.svg";
export { ReactComponent as FantomImage } from "./Fantom.svg";
export { ReactComponent as BscImage } from "./BSC.svg";
export { ReactComponent as AvalancheImage } from "./Avalanche.svg";
export { ReactComponent as AuroraImage } from "./Aurora.svg";
export { ReactComponent as HarmonyImage } from "./Harmony.svg";
